/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.nner;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author krisztian_csekme1
 */
public class Properties extends javax.swing.JDialog {
private Product pro;
private Point anchorPoint;
    /**
     * Creates new form Properties
     */
    public Properties(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        setCenter();
        setMoveAble();
    }
    
    
    
    
    
    

    
    void setCenter() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(((dim.width - this.getSize().width) / 2), ((dim.height - this.getSize().height) / 2));

    }
    
    
    public void init(Product product){
        
        if (product.RELEASE){
            RELEASE_BOX.setSelected(true);
        }else{
             RELEASE_BOX.setSelected(false);
        }
        
        
        if (product.getStation().isEngineering(product.getJobnumber())){
            ENGINEERING_BOX.setSelected(true);
        }else{
            ENGINEERING_BOX.setSelected(false);
        }
        
        if (product.getStation().isPassed(product.getJobnumber())){
            PASSING_BOX.setSelected(false);
        }else{
          PASSING_BOX.setSelected(true);  
        }
        Station st = product.getStation();
        pro = product;
        TEXT_JOB.setText(pro.getJobnumber());
        TEXT_NUMBER.setText(pro.getPartnumber());
        TEXT_COMMENT_PLANNER.setText(pro.getPlannerComment());
        TEXT_QTY.setText(Double.toString(pro.getQty()));
        TEXT_COMMENT.setText(pro.getComment());
        CODE_FORE_COLOR.setText(pro.getPartnumber());
        FORE_COLOR.setBackground(pro.getFGColor());
        BG_COLOR.setBackground(pro.getBGColor());
        CODE_FORE_COLOR.setForeground(pro.getFGColor());
        CODE_BG_COLOR.setBackground(pro.getBGColor());
        TEXT_DB_PER_HOUR.setText(null);
        TEXT_STARTUP_TIME.setText(Integer.toString(pro.getStartUpMin()));
        TEXT_DOWN_TIME.setText(Integer.toString(pro.getDownTimeMin()));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEXT_COMMENT = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        TEXT_JOB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TEXT_NUMBER = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TEXT_QTY = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        FORE_COLOR = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        BG_COLOR = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TEXT_STARTUP_TIME = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TEXT_DOWN_TIME = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TEXT_DB_PER_HOUR = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        RELEASE_BOX = new javax.swing.JCheckBox();
        ApplyButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        CODE_BG_COLOR = new javax.swing.JPanel();
        CODE_FORE_COLOR = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TEXT_COMMENT_PLANNER = new javax.swing.JTextField();
        ENGINEERING_BOX = new javax.swing.JCheckBox();
        PASSING_BOX = new javax.swing.JCheckBox();

        setUndecorated(true);
        setOpacity(0.9F);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(50, 30));
        jScrollPane1.setViewportView(TEXT_COMMENT);

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Jobszám:");

        TEXT_JOB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Partnumber:");

        TEXT_NUMBER.setEditable(false);
        TEXT_NUMBER.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Gyártandó mennyiség:");

        TEXT_QTY.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Szövegszín:");

        FORE_COLOR.setBackground(new java.awt.Color(255, 255, 255));
        FORE_COLOR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FORE_COLOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FORE_COLORMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FORE_COLORLayout = new javax.swing.GroupLayout(FORE_COLOR);
        FORE_COLOR.setLayout(FORE_COLORLayout);
        FORE_COLORLayout.setHorizontalGroup(
            FORE_COLORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );
        FORE_COLORLayout.setVerticalGroup(
            FORE_COLORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Háttérszín:");

        BG_COLOR.setBackground(new java.awt.Color(0, 51, 255));
        BG_COLOR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BG_COLOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BG_COLORMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BG_COLORLayout = new javax.swing.GroupLayout(BG_COLOR);
        BG_COLOR.setLayout(BG_COLORLayout);
        BG_COLORLayout.setHorizontalGroup(
            BG_COLORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );
        BG_COLORLayout.setVerticalGroup(
            BG_COLORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Betárazási idő (p):");

        TEXT_STARTUP_TIME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Komment:");

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Kitárazási idő (p):");

        TEXT_DOWN_TIME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Darab / Óra:");

        TEXT_DB_PER_HOUR.setBackground(new java.awt.Color(255, 0, 0));
        TEXT_DB_PER_HOUR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Minta:");

        RELEASE_BOX.setBackground(new java.awt.Color(255, 255, 255));
        RELEASE_BOX.setForeground(new java.awt.Color(102, 102, 102));
        RELEASE_BOX.setText("Release");
        RELEASE_BOX.setToolTipText("Bekapcsolt állapotban tervez a termékkel");

        ApplyButton.setText("Módosít");
        ApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Mégse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CODE_BG_COLOR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CODE_FORE_COLOR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CODE_FORE_COLOR.setText("jLabel9");

        javax.swing.GroupLayout CODE_BG_COLORLayout = new javax.swing.GroupLayout(CODE_BG_COLOR);
        CODE_BG_COLOR.setLayout(CODE_BG_COLORLayout);
        CODE_BG_COLORLayout.setHorizontalGroup(
            CODE_BG_COLORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CODE_BG_COLORLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CODE_FORE_COLOR, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CODE_BG_COLORLayout.setVerticalGroup(
            CODE_BG_COLORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CODE_BG_COLORLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CODE_FORE_COLOR))
        );

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/nner/IMG/close.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Termék beállításai:");

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Tervezői komment:");

        TEXT_COMMENT_PLANNER.setToolTipText("A tervezői komment nem jelenik meg a tervben!!!");
        TEXT_COMMENT_PLANNER.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        ENGINEERING_BOX.setBackground(new java.awt.Color(255, 255, 255));
        ENGINEERING_BOX.setForeground(new java.awt.Color(102, 102, 102));
        ENGINEERING_BOX.setText("Mérnöki");
        ENGINEERING_BOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENGINEERING_BOXActionPerformed(evt);
            }
        });

        PASSING_BOX.setBackground(new java.awt.Color(255, 255, 255));
        PASSING_BOX.setForeground(new java.awt.Color(102, 102, 102));
        PASSING_BOX.setText("Rejtés");
        PASSING_BOX.setToolTipText("Tervező segéd elől rejt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)
                        .addGap(435, 435, 435)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(154, 154, 154)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(TEXT_JOB, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TEXT_COMMENT_PLANNER, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(13, 13, 13)
                                .addComponent(FORE_COLOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(BG_COLOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel8)
                                .addGap(4, 4, 4)
                                .addComponent(CODE_BG_COLOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel5)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TEXT_STARTUP_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEXT_DOWN_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RELEASE_BOX)
                            .addComponent(PASSING_BOX)
                            .addComponent(ENGINEERING_BOX)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel10)
                        .addGap(7, 7, 7)
                        .addComponent(TEXT_DB_PER_HOUR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jButton1)
                        .addGap(7, 7, 7)
                        .addComponent(ApplyButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(TEXT_NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(11, 11, 11)
                                        .addComponent(TEXT_QTY, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel11))
                    .addComponent(jLabel12))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TEXT_JOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_COMMENT_PLANNER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TEXT_NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(TEXT_QTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(FORE_COLOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(BG_COLOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(CODE_BG_COLOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(TEXT_STARTUP_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(TEXT_DOWN_TIME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(RELEASE_BOX))
                    .addComponent(PASSING_BOX)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ENGINEERING_BOX)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(TEXT_DB_PER_HOUR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(ApplyButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyButtonActionPerformed
       pro.getStation().recalcJobs();
      
       
       pro.setJobnumber(TEXT_JOB.getText());
       pro.setQty(Double.parseDouble(TEXT_QTY.getText()));
       pro.setStartUpMin(Integer.parseInt(TEXT_STARTUP_TIME.getText()));
       pro.setDownTimeMin(Integer.parseInt(TEXT_DOWN_TIME.getText()));
       pro.setBGColor(BG_COLOR.getBackground());
       pro.setFGColor(FORE_COLOR.getBackground());
       pro.setComment(TEXT_COMMENT.getText());
       pro.setPlannerComment(TEXT_COMMENT_PLANNER.getText());
       
       if (PASSING_BOX.isSelected()){
           pro.getStation().setPassed(pro.getJobnumber(), Boolean.FALSE);
       }else{
           pro.getStation().setPassed(pro.getJobnumber(), Boolean.TRUE);
       }
       
       Station st = pro.getStation();
       pro.RELEASE = RELEASE_BOX.isSelected();
       
       
       
      
       if (ENGINEERING_BOX.isSelected()){
            pro.getStation().setEngineering(pro.getJobnumber(),Boolean.TRUE);
       }else{
            pro.getStation().setEngineering(pro.getJobnumber(), Boolean.FALSE);
       }
       
      
       if (TEXT_DB_PER_HOUR.getText().length()>0){
           int re = JOptionPane.showConfirmDialog(this, "Megváltoztatta az óránkénti darabszám kimenetet! Biztosan rögzíteni szeretné?","Figyelem!",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
           if (re == JOptionPane.YES_OPTION){
           double DB_P_H = Double.parseDouble(TEXT_DB_PER_HOUR.getText());
           pro.setCycle( ((3600 * ((double)pro.getEff()/100)) * pro.getPanelization()) / DB_P_H   );
           }else{
               TEXT_DB_PER_HOUR.setText(null);
           }
       }
       pro.resize();
       pro.repaint();
       //PLANS.get(MainForm.jTabbedPane.getSelectedIndex()).action.actionPerformed(null);
        pro.getStation().setNeedToSave();
        
         if (!pro.getStation().isExistinLoader(pro.getJobnumber()))
       pro.getStation().putJobtoLoader(pro.getJobnumber(), pro.getPartnumber(), pro.getQty());
        
        
        
        PlNner.PH.tick();
       setVisible(false);
    }//GEN-LAST:event_ApplyButtonActionPerformed

    private void FORE_COLORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FORE_COLORMouseClicked
        Color fore = JColorChooser.showDialog(null, "Betűszín kiválasztása", FORE_COLOR.getForeground());
        if (fore != null) {
            FORE_COLOR.setBackground(fore);
            CODE_FORE_COLOR.setForeground(fore);
        }
    }//GEN-LAST:event_FORE_COLORMouseClicked

    private void BG_COLORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG_COLORMouseClicked
        Color bg = JColorChooser.showDialog(null, "Háttérszín kiválasztása", BG_COLOR.getForeground());
        if ( bg != null) {
            BG_COLOR.setBackground(bg);
            CODE_BG_COLOR.setBackground(bg);
        }
    }//GEN-LAST:event_BG_COLORMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        setVisible(false);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void ENGINEERING_BOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENGINEERING_BOXActionPerformed
       if (ENGINEERING_BOX.isSelected()){
         //  PlNner.LS.init(pro);
        //   PlNner.LS.setVisible(true);
       }
    }//GEN-LAST:event_ENGINEERING_BOXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Properties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Properties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Properties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Properties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Properties dialog = new Properties(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

     private void setMoveAble() {
        /**
         * This handle is a reference to THIS because in next Mouse Adapter
         * "this" is not allowed
         */
        @SuppressWarnings("unused")
        final Properties handle = Properties.this;
        handle.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent e) {
                anchorPoint = e.getPoint();
            }

            @Override
            public void mouseDragged(MouseEvent me) {
                me.translatePoint(me.getComponent().getLocation().x, me.getComponent().getLocation().y);

                handle.setLocation(me.getX() - anchorPoint.x, me.getY() - anchorPoint.y);

            }

        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApplyButton;
    private javax.swing.JPanel BG_COLOR;
    private javax.swing.JPanel CODE_BG_COLOR;
    private javax.swing.JLabel CODE_FORE_COLOR;
    public javax.swing.JCheckBox ENGINEERING_BOX;
    private javax.swing.JPanel FORE_COLOR;
    private javax.swing.JCheckBox PASSING_BOX;
    public javax.swing.JCheckBox RELEASE_BOX;
    private javax.swing.JTextPane TEXT_COMMENT;
    private javax.swing.JTextField TEXT_COMMENT_PLANNER;
    private javax.swing.JTextField TEXT_DB_PER_HOUR;
    private javax.swing.JTextField TEXT_DOWN_TIME;
    public javax.swing.JTextField TEXT_JOB;
    public javax.swing.JTextField TEXT_NUMBER;
    public javax.swing.JTextField TEXT_QTY;
    private javax.swing.JTextField TEXT_STARTUP_TIME;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
