/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.nner;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FileDialog;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Csekme
 */
public class StationProperties extends javax.swing.JDialog {
Point anchorPoint;
String theme_dir;
private Station station;
private String bg_fname=null;
private ImageIcon BG;
    /**
     * Creates new form StationProperties
     */
    public StationProperties(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setCenter();
        setMoveAble();
    }

    void setCenter() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(((dim.width - this.getSize().width) / 2), ((dim.height - this.getSize().height) / 2));

    }
    
    
    public void reloadList(){
        this.theme_dir = "S:\\SiteData\\BUD1\\EMS\\planning\\[DEV_CENTER]\\PlannerFacelift\\THEMES";
        File files = new File(theme_dir);
        String[] themes = files.list();
        DefaultListModel model = new DefaultListModel();
        for (String elem: themes){
             model.addElement(elem);
        }
        LIST_THEMES.setModel(model);
    }
    
    public void init(){
        
        BG_PANEL.setBackground(station.BG_COLOR);
        FG_PANEL.setBackground(station.FG_COLOR);
        SEL_PANEL.setBackground(station.SELECTED_COLOR);
        HALF_PANEL.setBackground(station.HALF_VISIBLE);
        PROG_BG_PANEL.setBackground(station.BG_PROGRESS);
        PROG_FG_PANEL.setBackground(station.FG_PROGRESS);
        
        SW_FAMIL.setSelected(station.SW_FAMILY);
        SW_INDI.setSelected(station.SW_INDICATOR);
        SW_JOB.setSelected(station.SW_JOBINFO);
        SW_KOMMENT.setSelected(station.SW_COMMENT);
        SW_STATUS.setSelected(station.SW_STATUS_BAR);
        PROD_OPACITY.setValue((int) (station.products_alpha * 100));
        COMBO_STRING_ON_PROD.setSelectedIndex(station.products_onwrite_string);
        SW_JOB_NO.setSelected(station.SW_JOB_NO);
        SW_PN_NO.setSelected(station.SW_PN_NO);
        SW_SEQ.setSelected(station.SW_SEQ);
        SW_ID.setSelected(station.SW_ID);
        BG = station.BG_IMAGE;
        combox_img_pos.setSelectedIndex(station.img_pos);
        
        reloadList();
        
        
    }
    
    public void setVisible(Station station){
        this.station = station;
          init();
        setVisible(true);
      
    }
    
    
    public Theme getTheme(){
       Theme theme = new Theme();
        theme.BG_COLOR = BG_PANEL.getBackground();
        theme.BG_PROGRESS=PROG_BG_PANEL.getBackground();
        theme.FG_COLOR = FG_PANEL.getBackground();
        theme.FG_PROGRESS = PROG_FG_PANEL.getBackground();
        theme.HALF_VISIBLE = HALF_PANEL.getBackground();
        theme.SELECTED_COLOR = SEL_PANEL.getBackground();
        theme.BG = BG;
        theme.img_pos = combox_img_pos.getSelectedIndex();
        return theme;
    }
    
    
    public void repaint(){
        Theme theme = getTheme();
        
        
        
        station.SW_COMMENT = SW_KOMMENT.isSelected();
        station.SW_FAMILY = SW_FAMIL.isSelected();
        station.SW_INDICATOR =SW_INDI.isSelected();
        station.SW_JOBINFO=SW_JOB.isSelected();
        station.SW_STATUS_BAR=SW_STATUS.isSelected();
        station.SW_JOB_NO = SW_JOB_NO.isSelected();
        station.SW_PN_NO = SW_PN_NO.isSelected();
        station.SW_ID = SW_ID.isSelected();
        station.SW_SEQ = SW_SEQ.isSelected();
        
        station.setTheme(theme);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BG_PANEL = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        FG_PANEL = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        SEL_PANEL = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        HALF_PANEL = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        PROG_BG_PANEL = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PROG_FG_PANEL = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LIST_THEMES = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        combox_img_pos = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        SW_STATUS = new javax.swing.JCheckBox();
        SW_INDI = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        SW_FAMIL = new javax.swing.JCheckBox();
        SW_JOB = new javax.swing.JCheckBox();
        SW_KOMMENT = new javax.swing.JCheckBox();
        SW_JOB_NO = new javax.swing.JCheckBox();
        SW_PN_NO = new javax.swing.JCheckBox();
        SW_SEQ = new javax.swing.JCheckBox();
        SW_ID = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        PROD_OPACITY = new javax.swing.JSlider();
        jLabel14 = new javax.swing.JLabel();
        COMBO_STRING_ON_PROD = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        BUTTON_RESET = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        TEXT_STARTUP = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setTitle("Állomás beállítása");
        setUndecorated(true);
        setOpacity(0.9F);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/nner/IMG/close.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Állomás beállításai:");

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setName(""); // NOI18N

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Háttér szín:");

        BG_PANEL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        BG_PANEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BG_PANEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BG_PANELMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BG_PANELLayout = new javax.swing.GroupLayout(BG_PANEL);
        BG_PANEL.setLayout(BG_PANELLayout);
        BG_PANELLayout.setHorizontalGroup(
            BG_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        BG_PANELLayout.setVerticalGroup(
            BG_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Szöveg szín:");

        FG_PANEL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        FG_PANEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FG_PANEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FG_PANELMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FG_PANELLayout = new javax.swing.GroupLayout(FG_PANEL);
        FG_PANEL.setLayout(FG_PANELLayout);
        FG_PANELLayout.setHorizontalGroup(
            FG_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        FG_PANELLayout.setVerticalGroup(
            FG_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Kijelölés:");

        SEL_PANEL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        SEL_PANEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SEL_PANEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SEL_PANELMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SEL_PANELLayout = new javax.swing.GroupLayout(SEL_PANEL);
        SEL_PANEL.setLayout(SEL_PANELLayout);
        SEL_PANELLayout.setHorizontalGroup(
            SEL_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        SEL_PANELLayout.setVerticalGroup(
            SEL_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Halvány megjegyzés:");

        HALF_PANEL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        HALF_PANEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HALF_PANEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HALF_PANELMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HALF_PANELLayout = new javax.swing.GroupLayout(HALF_PANEL);
        HALF_PANEL.setLayout(HALF_PANELLayout);
        HALF_PANELLayout.setHorizontalGroup(
            HALF_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        HALF_PANELLayout.setVerticalGroup(
            HALF_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Státusz bár háttérszíne:");

        PROG_BG_PANEL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        PROG_BG_PANEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PROG_BG_PANEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PROG_BG_PANELMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PROG_BG_PANELLayout = new javax.swing.GroupLayout(PROG_BG_PANEL);
        PROG_BG_PANEL.setLayout(PROG_BG_PANELLayout);
        PROG_BG_PANELLayout.setHorizontalGroup(
            PROG_BG_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        PROG_BG_PANELLayout.setVerticalGroup(
            PROG_BG_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Státusz bár előtérszíne:");

        PROG_FG_PANEL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        PROG_FG_PANEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PROG_FG_PANEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PROG_FG_PANELMouseClicked(evt);
            }
        });
        PROG_FG_PANEL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PROG_FG_PANELKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout PROG_FG_PANELLayout = new javax.swing.GroupLayout(PROG_FG_PANEL);
        PROG_FG_PANEL.setLayout(PROG_FG_PANELLayout);
        PROG_FG_PANELLayout.setHorizontalGroup(
            PROG_FG_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        PROG_FG_PANELLayout.setVerticalGroup(
            PROG_FG_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        LIST_THEMES.setForeground(new java.awt.Color(102, 102, 102));
        LIST_THEMES.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        LIST_THEMES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LIST_THEMESMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(LIST_THEMES);

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Mentett témák:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/nner/IMG/playblue16.png"))); // NOI18N
        jButton2.setToolTipText("összeállítás mentése...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Háttérkép beállítások:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), java.awt.Color.gray)); // NOI18N
        jPanel5.setForeground(new java.awt.Color(102, 102, 102));

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Háttérkép:");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/nner/IMG/browse16.png"))); // NOI18N
        jButton3.setToolTipText("Tallóz");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/nner/IMG/close16.png"))); // NOI18N
        jButton4.setToolTipText("Eltávolítás");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Igazítás:");

        combox_img_pos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Középre igazít", "Ismétlő" }));
        combox_img_pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox_img_posActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(36, 36, 36)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(47, 47, 47)
                        .addComponent(combox_img_pos, 0, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jLabel10)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combox_img_pos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BG_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HALF_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SEL_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FG_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PROG_BG_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PROG_FG_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BG_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FG_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SEL_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HALF_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PROG_BG_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PROG_FG_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Téma beállítások", jPanel2);

        SW_STATUS.setText("Státusz bár mutatása");
        SW_STATUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SW_STATUSActionPerformed(evt);
            }
        });

        SW_INDI.setText("Indikátor mutatása");
        SW_INDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SW_INDIActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Segéd adatok:"));

        SW_FAMIL.setText("Termék család kijelzése");
        SW_FAMIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SW_FAMILActionPerformed(evt);
            }
        });

        SW_JOB.setText("JOB infó kijelzése");
        SW_JOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SW_JOBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SW_FAMIL)
                    .addComponent(SW_JOB))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SW_FAMIL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SW_JOB))
        );

        SW_KOMMENT.setText("Komment mutatása");
        SW_KOMMENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SW_KOMMENTActionPerformed(evt);
            }
        });

        SW_JOB_NO.setText("Jobszám kiíratása");
        SW_JOB_NO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SW_JOB_NOMouseReleased(evt);
            }
        });

        SW_PN_NO.setText("Partnumber kiíratása");
        SW_PN_NO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SW_PN_NOMouseReleased(evt);
            }
        });

        SW_SEQ.setText("Szekvencia kiíratása");
        SW_SEQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SW_SEQMouseReleased(evt);
            }
        });

        SW_ID.setText("ID szám kiíratása");
        SW_ID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SW_IDMouseReleased(evt);
            }
        });

        jLabel13.setText("Termékek átlátszósága:");
        jLabel13.setToolTipText("");

        PROD_OPACITY.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PROD_OPACITYStateChanged(evt);
            }
        });

        jLabel14.setText("Termékre ráírva:");

        COMBO_STRING_ON_PROD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semmi", "Partnumber", "Jobszám" }));
        COMBO_STRING_ON_PROD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMBO_STRING_ON_PRODActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SW_STATUS)
                    .addComponent(SW_INDI)
                    .addComponent(SW_KOMMENT)
                    .addComponent(SW_JOB_NO)
                    .addComponent(SW_PN_NO)
                    .addComponent(SW_SEQ)
                    .addComponent(SW_ID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addComponent(PROD_OPACITY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(COMBO_STRING_ON_PROD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PROD_OPACITY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(COMBO_STRING_ON_PROD)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(SW_STATUS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SW_INDI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SW_KOMMENT)
                        .addGap(18, 18, 18)
                        .addComponent(SW_JOB_NO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SW_PN_NO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SW_SEQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SW_ID)))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Megjelenés beállítások", jPanel3);

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Terv újra megjelölése Első Terv-nek:");

        BUTTON_RESET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/nner/IMG/reset_arrow.png"))); // NOI18N
        BUTTON_RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_RESETActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Tárazás átállítása a tervben szereplő termékekre:");

        jButton5.setText("Beállít");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BUTTON_RESET))
                    .addComponent(jLabel15)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(TEXT_STARTUP, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTON_RESET))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEXT_STARTUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(204, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Egyéb beállítások", jPanel6);

        jButton1.setText("Rendben");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void BG_PANELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BG_PANELMouseClicked
        Color fore = JColorChooser.showDialog(null, "Háttér kiválasztása", BG_PANEL.getBackground());
        if (fore != null) {
           BG_PANEL.setBackground(fore);
            repaint();
        }
    }//GEN-LAST:event_BG_PANELMouseClicked

    private void FG_PANELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FG_PANELMouseClicked
           Color fore = JColorChooser.showDialog(null, "Szövegszín kiválasztása", FG_PANEL.getBackground());
        if (fore != null) {
           FG_PANEL.setBackground(fore);
            repaint();
        }
    }//GEN-LAST:event_FG_PANELMouseClicked

    private void SEL_PANELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEL_PANELMouseClicked
           Color fore = JColorChooser.showDialog(null, "Kijelölés szín kiválasztása", SEL_PANEL.getBackground());
        if (fore != null) {
           SEL_PANEL.setBackground(fore);
            repaint();
        }
    }//GEN-LAST:event_SEL_PANELMouseClicked

    private void HALF_PANELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HALF_PANELMouseClicked
           Color fore = JColorChooser.showDialog(null, "Halvány megjegyzés szín kiválasztása", HALF_PANEL.getBackground());
        if (fore != null) {
           HALF_PANEL.setBackground(fore);
            repaint();
        }
    }//GEN-LAST:event_HALF_PANELMouseClicked

    private void PROG_BG_PANELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROG_BG_PANELMouseClicked
         Color fore = JColorChooser.showDialog(null, "Státusz bár háttér szín kiválasztása", PROG_BG_PANEL.getBackground());
        if (fore != null) {
           PROG_BG_PANEL.setBackground(fore);
            repaint();
        }
    }//GEN-LAST:event_PROG_BG_PANELMouseClicked

    private void PROG_FG_PANELKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PROG_FG_PANELKeyPressed
    
    }//GEN-LAST:event_PROG_FG_PANELKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PROG_FG_PANELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROG_FG_PANELMouseClicked
             Color fore = JColorChooser.showDialog(null, "Státuszbár előtér szín kiválasztása", PROG_FG_PANEL.getBackground());
        if (fore != null) {
           PROG_FG_PANEL.setBackground(fore);
            repaint();
        }
    }//GEN-LAST:event_PROG_FG_PANELMouseClicked

    private void SW_STATUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SW_STATUSActionPerformed
        repaint();
    }//GEN-LAST:event_SW_STATUSActionPerformed

    private void SW_INDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SW_INDIActionPerformed
        repaint();
    }//GEN-LAST:event_SW_INDIActionPerformed

    private void SW_KOMMENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SW_KOMMENTActionPerformed
        repaint();
    }//GEN-LAST:event_SW_KOMMENTActionPerformed

    private void SW_FAMILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SW_FAMILActionPerformed
        repaint();
    }//GEN-LAST:event_SW_FAMILActionPerformed

    private void SW_JOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SW_JOBActionPerformed
       repaint();
    }//GEN-LAST:event_SW_JOBActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try { 
        String filename = JOptionPane.showInputDialog(StationProperties.this,"Kérem adja meg a téma nevét!","Figyelem!",JOptionPane.QUESTION_MESSAGE);
        if (filename!=null){
        FileOutputStream fout = null;
        fout = new FileOutputStream(theme_dir + "\\" + filename);
        ObjectOutputStream os = new ObjectOutputStream(fout);
        
        os.writeObject(getTheme());
        os.flush();
        os.close();
        station.needToReloadThemes=true;
        
        }
        
    } catch (FileNotFoundException ex) {
        Logger.getLogger(StationProperties.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(StationProperties.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    reloadList();
    
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void LIST_THEMESMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LIST_THEMESMouseReleased
        if (LIST_THEMES.getSelectedIndex()>-1){
        String selected = LIST_THEMES.getSelectedValue().toString();
        
            try {
                              
                FileInputStream fis = new FileInputStream(theme_dir + "\\" + selected);
                ObjectInputStream ois = new ObjectInputStream(fis);
                Theme theme = (Theme)ois.readObject();
              
                station.setTheme(theme);
                init();
                                
                                
            } catch (FileNotFoundException ex) {
                
            } catch (IOException ex) {
                 
            } catch (ClassNotFoundException ex) {
                 
            }
            
        }
    }//GEN-LAST:event_LIST_THEMESMouseReleased

    private void SW_JOB_NOMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SW_JOB_NOMouseReleased
        repaint();
    }//GEN-LAST:event_SW_JOB_NOMouseReleased

    private void SW_PN_NOMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SW_PN_NOMouseReleased
        repaint();
    }//GEN-LAST:event_SW_PN_NOMouseReleased

    private void SW_SEQMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SW_SEQMouseReleased
        repaint();
    }//GEN-LAST:event_SW_SEQMouseReleased

    private void SW_IDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SW_IDMouseReleased
        repaint();
    }//GEN-LAST:event_SW_IDMouseReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FileDialog fd = new FileDialog(this, "Háttérkép kiválasztása", FileDialog.LOAD);
        fd.setDirectory("S:\\SiteData\\BUD1\\EMS\\planning\\[DEV_CENTER]\\PlannerFacelift\\BG");
        fd.setLocation(50, 50);
        fd.setVisible(true);
        if (fd.getFile() != null) {
            bg_fname = fd.getDirectory() + "\\" + fd.getFile();
            BG = new ImageIcon(bg_fname);
              repaint();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        station.BG_IMAGE=null;
        BG = null;
        bg_fname = null;
        repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void combox_img_posActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox_img_posActionPerformed
        repaint();
    }//GEN-LAST:event_combox_img_posActionPerformed

    private void BUTTON_RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_RESETActionPerformed
        station.isPlanA = true;
    }//GEN-LAST:event_BUTTON_RESETActionPerformed

    private void PROD_OPACITYStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PROD_OPACITYStateChanged
        station.products_alpha = (float)((double)PROD_OPACITY.getValue() /100);
        station.repaint();
    }//GEN-LAST:event_PROD_OPACITYStateChanged

    private void COMBO_STRING_ON_PRODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMBO_STRING_ON_PRODActionPerformed
       station.products_onwrite_string=COMBO_STRING_ON_PROD.getSelectedIndex();
    }//GEN-LAST:event_COMBO_STRING_ON_PRODActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     
        Integer startup;
        
        try{
            
            startup = Integer.parseInt(TEXT_STARTUP.getText()); 
            
            for (Product prod : station.PRODUCTS){
                prod.setStartUpMin(startup);
                prod.resize();
                prod.repaint();
            }
            
        }catch(Exception e){
            
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StationProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StationProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StationProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StationProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StationProperties dialog = new StationProperties(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
    private void setMoveAble() {
        /**
         * This handle is a reference to THIS because in next Mouse Adapter
         * "this" is not allowed
         */
        @SuppressWarnings("unused")
        final StationProperties handle = StationProperties.this;
        handle.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent e) {
                anchorPoint = e.getPoint();
            }

            @Override
            public void mouseDragged(MouseEvent me) {
                me.translatePoint(me.getComponent().getLocation().x, me.getComponent().getLocation().y);

                handle.setLocation(me.getX() - anchorPoint.x, me.getY() - anchorPoint.y);

            }

        });
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG_PANEL;
    private javax.swing.JButton BUTTON_RESET;
    private javax.swing.JComboBox COMBO_STRING_ON_PROD;
    private javax.swing.JPanel FG_PANEL;
    private javax.swing.JPanel HALF_PANEL;
    private javax.swing.JList LIST_THEMES;
    private javax.swing.JSlider PROD_OPACITY;
    private javax.swing.JPanel PROG_BG_PANEL;
    private javax.swing.JPanel PROG_FG_PANEL;
    private javax.swing.JPanel SEL_PANEL;
    private javax.swing.JCheckBox SW_FAMIL;
    private javax.swing.JCheckBox SW_ID;
    private javax.swing.JCheckBox SW_INDI;
    private javax.swing.JCheckBox SW_JOB;
    private javax.swing.JCheckBox SW_JOB_NO;
    private javax.swing.JCheckBox SW_KOMMENT;
    private javax.swing.JCheckBox SW_PN_NO;
    private javax.swing.JCheckBox SW_SEQ;
    private javax.swing.JCheckBox SW_STATUS;
    private javax.swing.JTextField TEXT_STARTUP;
    private javax.swing.JComboBox combox_img_pos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
